version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/ill.fi/neobeam/
    steps:
    - checkout

    # - run: go get -v -t -d ./... no dependencies, yet
    - run: go get -u github.com/stretchr/testify
    - run: go test -v ill.fi/neobeam/tests